begin;

create extension citext;

create table users(
    id int generated by default as identity primary key,
    email citext unique not null,
    password_hash text,
    created_at timestamp,
    updated_at timestamp
);

create function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger set_updated_at
before update on users
for each row
execute function update_updated_at_column();

commit;